export const UserMutationType =
{
  GET_LIST_USER_IN_PROGRESS: 'GET_LIST_USER_IN_PROGRESS',
  GET_LIST_USER_SUCCESS: 'GET_LIST_USER_SUCCESS',
  GET_LIST_USER_FAILED: 'GET_LIST_USER_FAILED'
}

export const ClientMutationType =
{
  GET_LIST_CLIENT_IN_PROGRESS: 'GET_LIST_CLIENT_IN_PROGRESS',
  GET_LIST_CLIENT_SUCCESS: 'GET_LIST_CLIENT_SUCCESS',
  GET_LIST_CLIENT_FAILED: 'GET_LIST_CLIENT_FAILED'
}

export const ClientUserMutationType =
{
  GET_LIST_CLIENT_USER_IN_PROGRESS: 'GET_LIST_CLIENT_USER_IN_PROGRESS',
  GET_LIST_CLIENT_USER_SUCCESS: 'GET_LIST_CLIENT_USER_SUCCESS',
  GET_LIST_CLIENT_USER_FAILED: 'GET_LIST_CLIENT_USER_FAILED'
}

export const SettlementApiTableTopMutationType =
{
  GET_LIST_DATA_TABLE_TOP_IN_PROGRESS: 'GET_LIST_DATA_TABLE_TOP_IN_PROGRESS',
  GET_LIST_DATA_TABLE_TOP_SUCCESS: 'GET_LIST_DATA_TABLE_TOP_SUCCESS',
  GET_LIST_DATA_TABLE_TOP_FAILED: 'GET_LIST_DATA_TABLE_TOP_FAILED'
}

export const SettlementApiTableBottomMutationType =
{
  GET_LIST_DATA_TABLE_BOTTOM_IN_PROGRESS: 'GET_LIST_DATA_TABLE_BOTTOM_IN_PROGRESS',
  GET_LIST_DATA_TABLE_BOTTOM_SUCCESS: 'GET_LIST_DATA_TABLE_BOTTOM_SUCCESS',
  GET_LIST_DATA_TABLE_BOTTOM_FAILED: 'GET_LIST_DATA_TABLE_BOTTOM_FAILED'
}

export const myInformationType =
{
  GET_USER_BY_ID_IN_PROGRESS: 'GET_USER_BY_ID_IN_PROGRESS',
  GET_USER_BY_ID_SUCCESS: 'GET_USER_BY_ID_SUCCESS',
  GET_USER_BY_ID_FAILED: 'GET_USER_BY_ID_FAILED',

  UPDATE_USER_INFORMATION_IN_PROGRESS: 'UPDATE_USER_INFORMATION_IN_PROGRESS',
  UPDATE_USER_INFORMATION_SUCCESS: 'UPDATE_USER_INFORMATION_SUCCESS',
  UPDATE_USER_INFORMATION_FAILED: 'UPDATE_USER_INFORMATION_FAILED'
}

export const ServiceManageMutationType = {
  GET_LIST_SERVICE_IN_PROGRESS: 'GET_LIST_SERVICE_IN_PROGRESS',
  GET_LIST_SERVICE_SUCCESS: 'GET_LIST_SERVICE_SUCCESS',
  GET_LIST_SERVICE_FAIL: 'GET_LIST_SERVICE_FAIL'
}

export const ClientManageMutationType = {
  CLIENT_MANAGE_GET_LIST_CLIENT: 'CLIENT_MANAGE_GET_LIST_CLIENT',
  CLIENT_MANAGE_CREATE_CLIENT: 'CLIENT_MANAGE_CREATE_CLIENT',
  CLIENT_MANAGE_DELETE_CLIENT: 'CLIENT_MANAGE_DELETE_CLIENT',
  CLIENT_MANAGE_CHANGE_STATUS_CLIENT: 'CLIENT_MANAGE_CHANGE_STATUS_CLIENT',
  CLIENT_MANAGE_GET_DETAIL_CLIENT: 'CLIENT_MANAGE_GET_DETAIL_CLIENT',
  CLIENT_MANAGE_GET_ACCOUNT_RELATE_TO_CLIENT: 'CLIENT_MANAGE_GET_ACCOUNT_RELATE_TO_CLIENT',
  CLIENT_MANAGE_GET_PERIOD_INFO: 'CLIENT_MANAGE_GET_PERIOD_INFO',
  CLIENT_MANAGE_SEND_INVITE_USER: 'CLIENT_MANAGE_SEND_INVITE_USER',
  CLIENT_MANAGE_GET_LIST_ADMIN: 'CLIENT_MANAGE_GET_LIST_ADMIN',
  CLIENT_MANAGE_GET_LIST_AGENCY: 'CLIENT_MANAGE_GET_LIST_AGENCY',
  CLIENT_MANAGE_ASSIGN_ROLE_FOR_USER: 'CLIENT_MANAGE_ASSIGN_ROLE_FOR_USER',
  CLIENT_MANAGE_UPDATE_CLIENT: 'CLIENT_MANAGE_UPDATE_CLIENT',
  CLIENT_MANAGE_REMOVE_USER_PERMISSION: 'CLIENT_MANAGE_REMOVE_USER_PERMISSION',
  CLIENT_MANAGE_GET_LIST_INDUSTRY: 'CLIENT_MANAGE_GET_LIST_INDUSTRY',
  CLIENT_MANAGE_GET_LIST_CLIENT_FOR_CONSIGNMENT: 'CLIENT_MANAGE_GET_LIST_CLIENT_FOR_CONSIGNMENT'
}
