export const GetFeedSettingType = {
  GET_FEED_SETTING_IN_PROGRESS: 'GET_FEED_SETTING_IN_PROGRESS',
  GET_FEED_SETTING_SUCCESS: 'GET_FEED_SETTING_SUCCESS',
  GET_FEED_SETTING_FAILED: 'GET_FEED_SETTING_FAILED'
}
export const GetListCollectedInformationType = {
  GET_COLLECTED_INFORMATION_IN_PROGRESS: 'GET_COLLECTED_INFORMATION_IN_PROGRESS',
  GET_COLLECTED_INFORMATION_SUCCESS: 'GET_COLLECTED_INFORMATION_SUCCESS',
  GET_COLLECTED_INFORMATION_FAILED: 'GET_COLLECTED_INFORMATION_FAILED'
}
export const TrackingTagsType = {
  UPDATE_TRACKING_TAGS_LOADING_STATUS: 'UPDATE_TRACKING_TAGS_LOADING_STATUS',
  UPDATE_TRACKING_TAGS_LOADING_VERIFY: 'UPDATE_TRACKING_TAGS_LOADING_VERIFY',
  UPDATE_TRACKING_TAGS_STATUS: 'UPDATE_TRACKING_TAGS_STATUS',
  UPDATE_TRACKING_TAGS_VERIFY: 'UPDATE_TRACKING_TAGS_VERIFY',
  GET_ALL_TRACKING_TAGS_IN_PROGRESS: 'GET_ALL_TRACKING_TAGS_IN_PROGRESS',
  GET_ALL_TRACKING_TAGS_SUCCESS: 'GET_ALL_TRACKING_TAGS_SUCCESS',
  GET_ALL_TRACKING_TAGS_FAILED: 'GET_ALL_TRACKING_TAGS_FAILED',
  CREATE_TRACKING_TAG_SUCCESS: 'CREATE_TRACKING_TAG_SUCCESS',
  CREATE_TRACKING_TAG_FAILED: 'CREATE_TRACKING_TAG_FAILED'
}

export const StateSummaryType = {
  UPDATE_FEED_SUMMARY_DATA_SUCCESS: 'UPDATE_FEED_SUMMARY_DATA_SUCCESS',
  UPDATE_FEED_SUMMARY_DATA_FAIL: 'UPDATE_FEED_SUMMARY_DATA_FAILED',
  UPDATE_PRODUCT_LIST_DATA_SUCCESS: 'UPDATE_PRODUCT_LIST_DATA_SUCCESS',
  UPDATE_PRODUCT_LIST_DATA_FAIL: 'UPDATE_PRODUCT_LIST_DATA_FAIL',
  UPDATE_SUGGEST_LIST_DATA_SUCCESS: 'UPDATE_SUGGEST_LIST_DATA_SUCCESS',
  UPDATE_SUGGEST_LIST_DATA_FAIL: 'UPDATE_SUGGEST_LIST_DATA_FAIL'
}
