export const TargetingReportMutationType =
{
  GET_CREATIVES_REPORTING_IN_PROGRESS: 'GET_CREATIVES_REPORTING_IN_PROGRESS',
  GET_CREATIVE_REPORTING_SUCCESS: 'GET_CREATIVE_REPORTING_SUCCESS',
  GET_CREATIVE_REPORTING_FAILED: 'GET_CREATIVE_REPORTING_FAILED',

  GET_USER_INTEREST_IN_PROGRESS: 'GET_USER_INTEREST_IN_PROGRESS',
  GET_USER_INTEREST_SUCCESS: 'GET_USER_INTEREST_SUCCESS',
  GET_USER_INTEREST_FAIL: 'GET_USER_INTEREST_FAIL'
}
