export const CreativeImageMutationType =
 {
   GET_CREATIVE_IMAGE_IN_PROGRESS: 'GET_CREATIVE_IMAGE_IN_PROGRESS',
   GET_CREATIVE_IMAGE_SUCCESS: 'GET_CREATIVE_IMAGE_SUCCESS',
   GET_CREATIVE_IMAGE_FAILD: 'GET_CREATIVE_IMAGE_FAILD',
   DELETE_CREATIVE_IMAGES_IN_PROGRESS: 'DELETE_CREATIVE_IMAGES_IN_PROGRESS',
   DELETE_CREATIVE_IMAGES_SUCCESS: 'DELETE_CREATIVE_IMAGES_SUCCESS',
   DELETE_CREATIVE_IMAGES_FAILD: 'DELETE_CREATIVE_IMAGES_FAILD',
   ACTIVATE_CREATIVE_IMAGES_IN_PROGRESS: 'ACTIVATE_CREATIVE_IMAGES_IN_PROGRESS',
   ACTIVATE_CREATIVE_IMAGES_SUCCESS: 'ACTIVATE_CREATIVE_IMAGES_SUCCESS',
   ACTIVATE_CREATIVE_IMAGES_FAILD: 'ACTIVATE_CREATIVE_IMAGES_FAILD',
   DEACTIVATE_CREATIVE_IMAGES_IN_PROGRESS: 'DEACTIVATE_CREATIVE_IMAGES_IN_PROGRESS',
   DEACTIVATE_CREATIVE_IMAGES_SUCCESS: 'DEACTIVATE_CREATIVE_IMAGES_SUCCESS',
   DEACTIVATE_CREATIVE_IMAGES_FAILD: 'DEACTIVATE_CREATIVE_IMAGES_FAILD',
   GET_IMAGE_SIZES_BY_ACCOUNT_IN_PROGRESS: 'GET_IMAGE_SIZES_BY_ACCOUNT_IN_PROGRESS',
   GET_IMAGE_SIZES_BY_ACCOUNT_SUCCESS: 'GET_IMAGE_SIZES_BY_ACCOUNT_SUCCESS',
   GET_IMAGE_SIZES_BY_ACCOUNT_FAILD: 'GET_IMAGE_SIZES_BY_ACCOUNT_FAILD'
 }
