export const accountPropertiesMutationTypes = {
  SET_ID: 'SET_ID',
  SET_CODE: 'SET_CODE',
  SET_TOKEN: 'SET_TOKEN',
  SET_INTRODUCTION: 'SET_INTRODUCTION',
  SET_SETTING: 'SET_SETTING',
  SET_STATUS: 'SET_STATUS',
  SET_NAME: 'SET_NAME',
  SET_AVATAR: 'SET_AVATAR',
  SET_ROLES: 'SET_ROLES',
  SET_USER: 'SET_USER'
}

