export const PerformanceReportMutationTypes = {
  GET_PERFORMANCE_REPORT_IN_PROGRESS: 'GET_PERFORMANCE_REPORT_IN_PROGRESS',
  GET_PERFORMANCE_REPORT_SUCCESS: 'GET_PERFORMANCE_REPORT_SUCCESS',
  GET_PERFORMANCE_REPORT_FAILED: 'GET_PERFORMANCE_REPORT_FAILED'
}
