export const layoutMutationTypes = {
  TOGGLE_SIDEBAR: 'TOGGLE_SIDEBAR',
  CLOSE_SIDEBAR: 'CLOSE_SIDEBAR',
  TOGGLE_DEVICE: 'TOGGLE_DEVICE',
  SET_LANGUAGE: 'SET_LANGUAGE',
  SET_FONT_NAME: 'SET_FONT_NAME',
  SET_SIZE: 'SET_SIZE'
}

