export const GetCampaignMutationType = {
  GET_CAMPAIGN_IN_PROGRESS: 'GET_CAMPAIGN_IN_PROGRESS',
  GET_CAMPAIGN_SUCCESS: 'GET_CAMPAIGN_SUCCESS',
  GET_CAMPAIGN_FAILED: 'GET_CAMPAIGN_FAILED'
}

export const CampaignManagementMutationType = {
  CAMPAIGN_CREATION_UPDATE_FORM_DATA: 'CAMPAIGN_CREATION_UPDATE_FORM_DATA',
  CAMPAIGN_CREATION_NEXT_STEP: 'CAMPAIGN_CREATION_NEXT_STEP',
  CAMPAIGN_CREATION_SET_INDUSTRY: 'CAMPAIGN_CREATION_SET_INDUSTRY',
  CAMPAIGN_CREATION_SET_DATA_LIST_CAMPAIGN: 'CAMPAIGN_CREATION_SET_DATA_LIST_CAMPAIGN',
  CAMPAIGN_CREATION_SET_DATA_LIST_AD_GROUP: 'CAMPAIGN_CREATION_SET_DATA_LIST_AD_GROUP',
  CAMPAIGN_CREATION_SET_DATA_LIST_IOS_APP: 'CAMPAIGN_CREATION_SET_DATA_LIST_IOS_APP',
  CAMPAIGN_CREATION_SET_DATA_LIST_ANDROID_APP: 'CAMPAIGN_CREATION_SET_DATA_LIST_ANDROID_APP',
  CAMPAIGN_CREATION_SET_DATA_LIST_COUNTRY: 'CAMPAIGN_CREATION_SET_DATA_LIST_COUNTRY',
  CAMPAIGN_CREATION_SET_DATA_LIST_LOCATION: 'CAMPAIGN_CREATION_SET_DATA_LIST_LOCATION',
  CAMPAIGN_CREATION_SET_DATA_LIST_LANGUAGE: 'CAMPAIGN_CREATION_SET_DATA_LIST_LANGUAGE',
  CAMPAIGN_CREATION_UPDATE_FORM_DATA_DEEP: 'CAMPAIGN_CREATION_UPDATE_FORM_DATA_DEEP',
  CAMPAIGN_CREATION_SET_DATA_LIST_DEVICE: 'CAMPAIGN_CREATION_SET_DATA_LIST_DEVICE'
}
