export const GetCampaignMutationType = {
  GET_CAMPAIGN_IN_PROGRESS: 'GET_CAMPAIGN_IN_PROGRESS',
  GET_CAMPAIGN_SUCCESS: 'GET_CAMPAIGN_SUCCESS',
  GET_CAMPAIGN_FAILED: 'GET_CAMPAIGN_FAILED'
}

export const SelectDateFilterSelectionType = {
  SELECT_DATE_FILTER_SELECTION: 'SELECT_DATE_FILTER_SELECTION',
  UPDATE_STATUS_FILTER_TYPE: 'UPDATE_STATUS_FILTER_TYPE'
}

export const CampaignManagementMutationType = {
  CAMPAIGN_CREATION_UPDATE_FORM_DATA: 'CAMPAIGN_CREATION_UPDATE_FORM_DATA',
  CAMPAIGN_CREATION_UPDATE_CAMPAIGN_NAME: 'CAMPAIGN_CREATION_UPDATE_CAMPAIGN_NAME',
  CAMPAIGN_CREATION_NEXT_STEP: 'CAMPAIGN_CREATION_NEXT_STEP',
  CAMPAIGN_CREATION_SET_INDUSTRY: 'CAMPAIGN_CREATION_SET_INDUSTRY',
  CAMPAIGN_CREATION_SET_DATA_LIST_CAMPAIGN: 'CAMPAIGN_CREATION_SET_DATA_LIST_CAMPAIGN',
  CAMPAIGN_CREATION_SET_DATA_LIST_AD_GROUP: 'CAMPAIGN_CREATION_SET_DATA_LIST_AD_GROUP',
  CAMPAIGN_CREATION_SET_DATA_LIST_IOS_APP: 'CAMPAIGN_CREATION_SET_DATA_LIST_IOS_APP',
  CAMPAIGN_CREATION_SET_DATA_LIST_ANDROID_APP: 'CAMPAIGN_CREATION_SET_DATA_LIST_ANDROID_APP',
  CAMPAIGN_CREATION_SET_DATA_LIST_COUNTRY: 'CAMPAIGN_CREATION_SET_DATA_LIST_COUNTRY',
  CAMPAIGN_CREATION_SET_DATA_LIST_LOCATION: 'CAMPAIGN_CREATION_SET_DATA_LIST_LOCATION',
  CAMPAIGN_CREATION_SET_DATA_LIST_LANGUAGE: 'CAMPAIGN_CREATION_SET_DATA_LIST_LANGUAGE',
  CAMPAIGN_CREATION_SET_DATA_LIST_CARRIER: 'CAMPAIGN_CREATION_SET_DATA_LIST_CARRIER',
  CAMPAIGN_CREATION_SET_DATA_LIST_BROWSER: 'CAMPAIGN_CREATION_SET_DATA_LIST_BROWSER',
  CAMPAIGN_CREATION_SET_DATA_LIST_CUSTOM_USER_GROUP: 'CAMPAIGN_CREATION_SET_DATA_LIST_CUSTOM_USER_GROUP',
  CAMPAIGN_CREATION_SET_DATA_LIST_MANUFACTURES: 'CAMPAIGN_CREATION_SET_DATA_LIST_MANUFACTURES',
  CAMPAIGN_CREATION_SET_DATA_LIST_PRODUCT_FEED: 'CAMPAIGN_CREATION_SET_DATA_LIST_PRODUCT_FEED',
  CAMPAIGN_CREATION_SET_DATA_LIST_PRODUCT: 'CAMPAIGN_CREATION_SET_DATA_LIST_PRODUCT',
  CAMPAIGN_CREATION_UPDATE_FORM_DATA_DEEP: 'CAMPAIGN_CREATION_UPDATE_FORM_DATA_DEEP',
  CAMPAIGN_CREATION_SET_DATA_LIST_DEVICE: 'CAMPAIGN_CREATION_SET_DATA_LIST_DEVICE',
  CAMPAIGN_CREATION_GET_PROBABILITY_OF_PURCHASE: 'CAMPAIGN_CREATION_GET_PROBABILITY_OF_PURCHASE',
  CAMPAIGN_CREATION_SET_ERROR_CAMPAIGN: 'CAMPAIGN_CREATION_SET_ERROR_CAMPAIGN',
  CAMPAIGN_CREATION_SET_DATA_LIST_TRACKING_COMPANIES: 'CAMPAIGN_CREATION_SET_DATA_LIST_TRACKING_COMPANIES',
  CAMPAIGN_CREATION_SET_DATA_LIST_TRACKING_CONVERSATION_TYPE: 'CAMPAIGN_CREATION_SET_DATA_LIST_TRACKING_CONVERSATION_TYPE',
  CAMPAIGN_CREATION_SET_DATA_LIST_SITE_BEHAVIORS: 'CAMPAIGN_CREATION_SET_DATA_LIST_SITE_BEHAVIORS',
  CAMPAIGN_CREATION_SET_DATA_LIST_PROBABILITY_GRADES: 'CAMPAIGN_CREATION_SET_DATA_LIST_PROBABILITY_GRADES',
  CAMPAIGN_CREATION_SET_DATA_LIST_PRODUCT_FEED_CATEGORY_CPC: 'CAMPAIGN_CREATION_SET_DATA_LIST_PRODUCT_FEED_CATEGORY_CPC',
  CAMPAIGN_CREATION_SET_DATA_FORECAST_OF_CONVERSION_CALCULATED: 'CAMPAIGN_CREATION_SET_DATA_FORECAST_OF_CONVERSION_CALCULATED',
  SET_DATA_LIST_USER_INTEREST_DIRECTORIES: 'SET_DATA_LIST_USER_INTEREST_DIRECTORIES',
  SET_DATA_LIST_ARTICLE_TOPIC_DIRECTORY: 'SET_DATA_LIST_ARTICLE_TOPIC_DIRECTORY',
  CAMPAIGN_CREATION_SET_REVENUE_RANGE: 'CAMPAIGN_CREATION_SET_REVENUE_RANGE',
  CAMPAIGN_CREATION_SET_DATA_LIST_OS: 'CAMPAIGN_CREATION_SET_DATA_LIST_OS'
}

export const CampaignReportMutationType = {
  CAMPAIGN_REPORT_GET_SET_OF_COLUMNS: 'CAMPAIGN_REPORT_GET_SET_OF_COLUMNS',
  CAMPAIGN_REPORT_GET_LIST_COLUMNS: 'CAMPAIGN_REPORT_GET_LIST_COLUMNS',
  CAMPAIGN_REPORT_DELETE_SET_OF_COLUMNS: 'CAMPAIGN_REPORT_DELETE_SET_OF_COLUMNS'
}

export const DailyReportMutationType = {
  DAILY_REPORT_GET_SET_OF_COLUMNS: 'DAILY_REPORT_GET_SET_OF_COLUMNS',
  DAILY_REPORT_GET_LIST_COLUMNS: 'DAILY_REPORT_GET_LIST_COLUMNS',
  DAILY_REPORT_DELETE_SET_OF_COLUMNS: 'DAILY_REPORT_DELETE_SET_OF_COLUMNS'
}
